<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>1.3.3</Version>
    <AssemblyName>BoxMate</AssemblyName>
    <Description>Cross-platform BOXROOM mod manager</Description>
    <RepositoryUrl>https://github.com/MidgetBrony/BoxMate</RepositoryUrl>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\BoxMate.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GitHubClientId Condition="'$(GitHubClientId)' == ''">Iv23liNqCz2boJrdPad1</GitHubClientId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\BoxMate.ico" />
    <AssemblyMetadata Include="GitHubClientId" Value="$(GitHubClientId)" />
  </ItemGroup>
</Project>
